### PR TITLE
fix connecting to wrong host bug

### PR DESCRIPTION
**Pull request by jhej**
the hostname was declared as a constant and inside the if block a new local hostname variable was created, which did not affect the first variable. In other words, it always connected to 127.0.0.1 no matter what hostname was specified.

### CODE REVIEW

**Comment by markuman** [comment]
Oh, thank you!

**Comment by jhej** [comment]
one more problem observed. I've switched to using the pipeline, but had to switch back since I would get a segmentation fault from time to time (what I did was send cca 4000 lpush statements in a pipeline). So there are probably still some problems lingering somewhere in the current implementation. (may also be related to reusing existing connections, but I don't know)

**Comment by markuman** [comment]
Well, maybe. But maybe it's related to the pipeline implementation itself too.
There are problems with the reuse of the variables I guess.

*  `command` https://github.com/markuman/go-redis/blob/master/mex/redis_.cpp#L248,
*  `key` https://github.com/markuman/go-redis/blob/master/mex/redis_.cpp#L259
*  `value`. https://github.com/markuman/go-redis/blob/master/mex/redis_.cpp#L270

I don't know if they need to be freed after each usage (when I tried that I got a sefault too).

**Comment by markuman** [comment]
Another workaround could be to use only one  `LPUSH` as far as your list isn't generates just in time. I use it with `RPUSH` for saving arrays: https://github.com/markuman/go-redis/blob/master/inst/redis.m#L321

**Comment by jhej** [comment]
Yeah, that could be the problem. You're only allocating memory but not deallocating it. I think you should do a mxFree(command) after you call redis in the cpp file.

At the moment I just use one LPUSH at a time and that seems to work.

**Comment by markuman** [comment]
I've committed it. Please try. 

With one-time LPUSH I mean

`LPUSH mylist 1 2 3 4 5 6 value etc` instead of

    LPUSH mylist 1
    LPUSH mylist 2
    ....

But when you're going to push whitespace values, this will fail.

**Comment by jhej** [comment]
Still doesn't work, I get a segmentation fault right away.

**Comment by markuman** [comment]
hmmm have you a code to reproduce it?

    r = redis();

    for n = 1:10000
      r.call({'LPUSH' 'mylist' num2str(n)});
    end


    for n = 1:10000
      r = r.pipeline({'LPUSH' 'mylist' num2str(n)});
    end

    r = r.execute();


this works in Linux without segfault

* Octave 4.0.0
* MATLAB Version: 8.5.0.197613 (R2015a)
* hiredis 0.13.1
* GCC 5.2.0

**Comment by jhej** [comment]
r = redis();

for n=1:10000
  r = r.pipeline({'LPUSH', 'test_queue', 'test string'});
end

r.execute();

always gives me a segmentation fault:
0x00007ffff7451ab8 in matrix::detail::noninlined::mx_array_api::mxGetCell(mxArray_tag const*, unsigned long) () from MATLAB/R2014a/bin/glnxa64/libmx.so

**Comment by markuman** [comment]
I cannot reproduce it. Not with my matlab version, nor with octave.

Can you uncomment line 31 https://github.com/markuman/go-redis/blob/master/mex/redis_.cpp#L31 recompile `redis_.cpp` and rerun the script above to see how far it comes?

**Comment by jhej** [comment]
I pulled the code where you introduced some checks and now it seems to be working, thanks a lot.

**Comment by markuman** [comment]
Oh cool. Thanks for the reply.

**Pull request merged**
