### PR TITLE
reuse an existing redis connection (needed to convert to c++)

### PR DESCRIPTION
**Pull request by jhej**
I found an existing solution (the class handle header file) and implemented it. I tried it and it seems to work, but I needed to convert the code to C++. I rewrote the redis mex function to take an string instruction as the first argument based on which it either creates a new connection, deletes a connection or sends a command to the redis server. So now once finished it is good to call the r.delete() function to close the connection.

### CODE REVIEW

**Comment by markuman** [comment]
Ok cool! Thx.
I've made some changes.
* in `redis.m`, properties `precision` and `batchsize` have to be public.
* I thow out the "change database number" test in `test_redis.m`, because changing the database doesn't work anymore in the same session. Maybe this can be implemented again too. But I'm not sure.

**Comment by markuman** [comment]
And there are now manycompiler warnings which I can't solve ad-hoc

    redis_.cpp:64:15: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         key       = "";


Or

    warning: ISO C++ 1998 does not support 'long long'

Which is declared in hiredis.h, so it's upstream. Or there are some compiler settings which solve it?!

**Comment by markuman** [comment]
Ok, more or less every warning is fixed. Only one is left which is a upstream warning in hiredis https://github.com/redis/hiredis/blob/master/sds.h#L47

    ✔ ~/git/origingoredis/mex [master|✚ 1…5] 
    20:51 $ gcc -fPIC -std=c++11 -I /usr/include/octave-4.0.0/octave/ -lm -I /usr/include/hiredis/ -lhiredis -shared -O2 -pedantic redis_.cpp -o redis_.mex
    In file included from /usr/include/hiredis/hiredis.h:40:0,
                     from redis_.cpp:20:
    /usr/include/hiredis/sds.h:47:14: warning: ISO C++ forbids zero-size array 'buf' [-Wpedantic]
         char buf[];
              ^

a simple `char *buf;` will fix it.

**Comment by markuman** [comment]
I've add a `db()` method to `redis.m` to change the database.

**Comment by jhej** [comment]
I've looked at it, it would probably be better to implement a changeDB within redis.cpp and use the existing connection. If you leave it as is, it is better to first close the current connection before opening a new one (i.e. call redis_('delete') before calling redis_('new')).

**Comment by markuman** [comment]
Can you provide a changeDB function implemented in redis.cpp?

**Pull request merged**
