### PR TITLE
native hiredis support for whitespace in values

### PR DESCRIPTION
**Pull request by jhej**
Needed support for whitespace in values (where serialization failed, because needed the strings in redis non-serialized), can be done natively with hiredis, can be implemented in a better way and can be made more general, but just letting you know in case you find anything useful

### CODE REVIEW

**Comment by markuman** [comment]
The boolean definition is fixed in upstream now http://hg.savannah.gnu.org/hgweb/octave/rev/54eec9c180cb
But I made some changes as described above with the cell input. So `get` and `set` in the `redis()` class don't do magic anymore.

**Comment by jhej** [comment]
Thanks a lot for the code update!

**Comment by markuman** [comment]
I've made some more changes in the `redis.m` class, because there where some errors which made some keys unavailable after setting through class usage. You should pull if you're working with whitespace keys.
Furthermore, I've expand the `test_redis.m` script in `mex` folder a lot for faster detection when I break things.

**Comment by jhej** [comment]
I've run into the following problem.

I do lot's of LPUSH / LPOP commands and pretty soon I get a hiredis error, which seems to be related to the fact, that for each LPUSH / LPOP command a new TCP redis connection is created and the system eventually has trouble freeing up new sockets. The best solution would be to reuse the created redis connection in the c-code (not sure how this could be done). Pipelining the commands could also help, however I would need go-redis to return redis replies for each pipelined command.

So I was wondering whether you have any good ideas on how to go about doing this, or if you plan to implement any of this in the near future, before I go try implement either of the methods.

**Comment by markuman** [comment]
When testing pipeline in go-redis I run into the same problems with linux. One workaround is to increase the limit of open files (when you're using linux too).

In `/etc/security/limits.conf` for example

    markus     soft    nofile      10000
    markus     hard    nofile      10000

But you need to restart I guess.

>  The best solution would be to reuse the created redis connection in the c-code (not sure how this could be done).

+1 Indeed! But I've no idea too :)

> So I was wondering whether you have any good ideas on how to go about doing this, or if you plan to implement any of this in the near future, before I go try implement either of the methods.

Currently (I'll going to put this in the pipeline_branch in the next hours) I'm implementing the whitespace thing for pipeline. It already works 100% with Matlab, but Octave made some problems when mixing different number of commands.

So I would like if you can implement the reuse of the connection. But when you'll try to return each reply of pipeline commands, it's cool too. Maybe the return should be optional then (but I'm not sure how other clients handle this).

**Pull request merged**
